# Generated by Django 5.0.1 on 2024-01-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_model_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='image',
        ),
        migrations.AddField(
            model_name='marka',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
