# Generated by Django 5.0.1 on 2024-01-26 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_model_image_marka_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='marka',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.model'),
        ),
    ]
