# Generated by Django 5.0.1 on 2024-01-26 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_car_marka_delete_marka'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='model',
        ),
        migrations.AddField(
            model_name='car',
            name='marka',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.marka'),
        ),
        migrations.DeleteModel(
            name='Model',
        ),
    ]
