# Generated by Django 5.0.1 on 2024-01-26 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_car_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
    ]
